---
- hosts: all
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles

  tasks:
    # - include: tasks/ansible-setup.yml
    - include: tasks/vim.yml
    - include: tasks/flux.yml
    - include: tasks/iterm.yml
    - include: tasks/karabiner.yml
    - include: tasks/zsh.yml
    - include: tasks/dock.yml
