---
  - name: check if homebrew zsh location is in shell settings
    command: grep -Fxq "/usr/local/bin/zsh" /etc/shells
    register: checkMyShellSettings
    always_run: yes
    ignore_errors: yes
    changed_when: False

  - name: add /usr/local/bin/zsh to shell settings
    command: sudo -s 'echo /usr/local/bin/zsh >> /etc/shells'
    when: checkMyShellSettings|failed

  - name: change shell assigned to user
    command: chsh -s /usr/local/bin/zsh
    when: checkMyShellSettings|failed

  - name: download oh my zsh
    git:
      repo: git://github.com/robbyrussell/oh-my-zsh.git
      dest: ~/.oh-my-zsh
